services:
  db:
    image: postgres:14
    container_name: "${APP_NAME}-database"
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - restapi
    volumes:
      - psqldb:/var/lib/postgres/data
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${APP_NAME}-api"
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - db
    networks:
      - restapi

volumes:
  psqldb:

networks:
  restapi:
    driver: bridge