services:
  db:
    container_name: ${APP_NAME}-mongo
    image: mongo:8.0.3
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT:-27017}:27017
    networks:
      - restapi
    volumes:
      - mongodb:/data/db
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${APP_NAME}-api"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD} 
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - db
    networks:
      - restapi

volumes:
  mongodb:

networks:
  restapi:
    driver: bridge