name: Docker Image CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v3

            - name: Build the Docker image
              uses: hoverkraft-tech/compose-action@v2.0.1
              with:
                 compose-file: "./docker-compose.yml"
                 run: docker-compose up --build -d