name: Docker Image CI

on:
    push

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v2

            - name: Install Docker Compose
              run: sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose sudo chmod +x /usr/local/bin/docker-compose docker-compose --version
              continue-on-error: false

            - name: Build the Docker image
              run: docker-compose up --build -d